# Generated by Django 5.2.2 on 2025-06-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.PositiveIntegerField()),
                ('ty', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canvas')),
            ],
            options={
                'unique_together': {('canvas', 'tx', 'ty')},
            },
        ),
    ]
